"""`sysmaint install` — first-time interactive setup on a new box.

Walks the operator through:
1. Creating /etc/sysmaint/ with correct permissions.
2. Prompting for SMTP credentials and writing config + password files.
3. Installing the systemd unit files into /etc/systemd/system/.
4. Enabling the weekly update timer (pi-hole timer is left disabled —
   operators flip it on per-box only on DNS servers).
5. Sending a test email so the operator can confirm the wiring works.
"""

from __future__ import annotations

import getpass
import logging
import os
import shutil
import subprocess
import sys
from importlib import resources
from pathlib import Path

from sysmaint.core import email as email_mod
from sysmaint.core.config import (
    DEFAULT_CONFIG_PATH,
    DEFAULT_PASSWORD_PATH,
    require_root,
)
from sysmaint.core.runner import run_command

SYSTEMD_DIR = Path("/etc/systemd/system")
ETC_DIR = Path("/etc/sysmaint")
LOG_DIR = Path("/var/log")


def execute(logger: logging.Logger, *, non_interactive: bool = False) -> int:
    """Run the interactive installer. Returns process exit code."""
    require_root()

    print("=" * 60)
    print("  sysmaint install — first-time setup")
    print("=" * 60)
    print()

    if (
        DEFAULT_CONFIG_PATH.exists()
        and not non_interactive
        and not _confirm(
            f"{DEFAULT_CONFIG_PATH} already exists. Overwrite?", default=False
        )
    ):
        print("Aborting. Existing config left untouched.")
        return 1

    if non_interactive:
        print("Non-interactive mode: skipping credential prompt.")
        if not DEFAULT_CONFIG_PATH.exists():
            print(
                "ERROR: --non-interactive requires an existing config at "
                f"{DEFAULT_CONFIG_PATH}",
                file=sys.stderr,
            )
            return 1
    else:
        _prompt_and_write_config(logger)

    _install_systemd_units(logger)
    _enable_default_timers(logger)

    if not non_interactive:
        _send_test_email(logger)

    print()
    print("Install complete. Useful commands:")
    print("  sudo sysmaint status                 # current state")
    print("  sudo systemctl list-timers sysmaint* # see next scheduled run")
    print("  sudo journalctl -u sysmaint-update.service -f")
    return 0


def _prompt_and_write_config(logger: logging.Logger) -> None:
    print("Email notification setup (Gmail SMTP relay):")
    print()
    from_addr = _prompt("Sender Gmail address", required=True)
    to_addr = _prompt("Recipient address (where the notifications go)", required=True)
    smtp_server = _prompt("SMTP server", default="smtp.gmail.com")
    smtp_port = _prompt("SMTP port", default="587")
    print()
    print("Gmail App Password (16 chars, generated at myaccount.google.com → Security):")
    password = getpass.getpass("  Password (input hidden): ").strip()
    if not password:
        raise RuntimeError("Password cannot be empty")

    print()
    auto_reboot = _confirm(
        "Auto-reboot during maintenance window when an upgrade requires it?",
        default=False,
    )
    services_default = "sshd,postfix"
    services = _prompt(
        f"Comma-separated services to watch [{services_default}]",
        default=services_default,
    )

    ETC_DIR.mkdir(parents=True, exist_ok=True)
    ETC_DIR.chmod(0o755)

    # Write password file first, locked down, then reference it from the
    # main config. Permission failure is loud — we'd rather abort than
    # ship a world-readable credential.
    DEFAULT_PASSWORD_PATH.write_text(password + "\n")
    DEFAULT_PASSWORD_PATH.chmod(0o600)
    os.chown(DEFAULT_PASSWORD_PATH, 0, 0)
    logger.info("Wrote %s (mode=0600)", DEFAULT_PASSWORD_PATH)

    config_text = _render_config(
        from_addr=from_addr,
        to_addr=to_addr,
        smtp_server=smtp_server,
        smtp_port=smtp_port,
        auto_reboot=auto_reboot,
        services=services,
    )
    DEFAULT_CONFIG_PATH.write_text(config_text)
    DEFAULT_CONFIG_PATH.chmod(0o640)
    os.chown(DEFAULT_CONFIG_PATH, 0, 0)
    logger.info("Wrote %s (mode=0640)", DEFAULT_CONFIG_PATH)


def _render_config(
    *,
    from_addr: str,
    to_addr: str,
    smtp_server: str,
    smtp_port: str,
    auto_reboot: bool,
    services: str,
) -> str:
    return f"""\
# /etc/sysmaint/sysmaint.conf — generated by `sysmaint install`
# Adjust by hand and re-run `sudo systemctl restart sysmaint-update.timer`
# if you change the schedule via this file (you can't from here, but won't hurt).

[email]
from = {from_addr}
to = {to_addr}
smtp_server = {smtp_server}
smtp_port = {smtp_port}
password_file = {DEFAULT_PASSWORD_PATH}

[update]
# When true, will reboot after an upgrade if /var/run/reboot-required exists
# AND the current time falls in the window below. When false, the email
# just flags REBOOT REQUIRED and you reboot manually.
auto_reboot = {'true' if auto_reboot else 'false'}
reboot_window_start = 03:00
reboot_window_end = 05:00
include_dist_upgrade = true

[notify]
# Always emails on failure or reboot-required. These toggles only affect
# the "clean" paths.
on_success = true
on_no_changes = false

[monitor]
# Mounts crossing this percent trigger an ALERT line in the email.
disk_threshold_percent = 85
# Comma-separated systemd services to report status for.
services = {services}
"""


def _install_systemd_units(logger: logging.Logger) -> None:
    """Copy bundled .service and .timer files into /etc/systemd/system/."""
    SYSTEMD_DIR.mkdir(parents=True, exist_ok=True)
    units = [
        "sysmaint-update.service",
        "sysmaint-update.timer",
        "sysmaint-pihole.service",
        "sysmaint-pihole.timer",
    ]
    for name in units:
        src_path = resources.files("sysmaint.data.systemd").joinpath(name)
        with resources.as_file(src_path) as src:
            dest = SYSTEMD_DIR / name
            shutil.copy(src, dest)
            dest.chmod(0o644)
            logger.info("Installed %s", dest)
    run_command(["systemctl", "daemon-reload"], timeout=30, logger=logger)


def _enable_default_timers(logger: logging.Logger) -> None:
    """Turn on the weekly update timer. Pi-hole timer stays disabled."""
    run_command(
        ["systemctl", "enable", "--now", "sysmaint-update.timer"],
        timeout=30,
        logger=logger,
    )
    print()
    print("Enabled: sysmaint-update.timer (weekly, Sun ~03:00 + jitter)")
    print("Not enabled: sysmaint-pihole.timer (only enable on DNS boxes)")
    print("  → sudo systemctl enable --now sysmaint-pihole.timer")


def _send_test_email(logger: logging.Logger) -> None:
    from sysmaint.core.config import load_config

    config = load_config()
    print()
    print("Sending test email...")
    try:
        email_mod.send_email(
            from_addr=config.email.from_addr,
            to_addr=config.email.to_addr,
            smtp_server=config.email.smtp_server,
            smtp_port=config.email.smtp_port,
            password=config.email.password,
            subject="sysmaint install — test email",
            body=(
                "This is the test email from `sysmaint install`.\n"
                "If you got this, the relay is working correctly."
            ),
            logger=logger,
        )
        print(f"  -> sent to {config.email.to_addr}")
    except email_mod.EmailError as exc:
        print(f"  -> FAILED: {exc}")
        print("     Check /var/log/sysmaint.log and the Gmail app password.")


def _prompt(question: str, *, default: str = "", required: bool = False) -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        answer = input(f"  {question}{suffix}: ").strip()
        if not answer and default:
            return default
        if not answer and required:
            print("  (required)")
            continue
        return answer


def _confirm(question: str, *, default: bool = False) -> bool:
    suffix = "[Y/n]" if default else "[y/N]"
    answer = input(f"  {question} {suffix}: ").strip().lower()
    if not answer:
        return default
    return answer in ("y", "yes")


def uninstall(logger: logging.Logger) -> int:
    """Remove timers + config. Used by `sysmaint uninstall`."""
    require_root()
    units = [
        "sysmaint-update.timer",
        "sysmaint-update.service",
        "sysmaint-pihole.timer",
        "sysmaint-pihole.service",
    ]
    for name in units:
        # Best-effort disable; ignore failures (unit may already be gone).
        subprocess.run(
            ["systemctl", "disable", "--now", name],
            capture_output=True,
            text=True,
            check=False,
            timeout=30,
        )
        target = SYSTEMD_DIR / name
        if target.exists():
            target.unlink()
            logger.info("Removed %s", target)
    subprocess.run(
        ["systemctl", "daemon-reload"], capture_output=True, check=False, timeout=30
    )
    print(
        f"Timers and unit files removed. Config preserved at {ETC_DIR}\n"
        f"To delete config too: sudo rm -rf {ETC_DIR}"
    )
    return 0
