"""Install and configure Postfix as a Gmail SMTP relay.

This is a one-shot setup command. It assumes:
- The box is fresh / Postfix is not already configured.
- The operator wants the standard "satellite system" topology where
  the local Postfix relays through Gmail using an app password.
- The sysmaint config (/etc/sysmaint/sysmaint.conf) is already populated;
  we read from there rather than re-prompting for the same values.
"""

from __future__ import annotations

import logging
from pathlib import Path

from sysmaint.core.config import Config, require_root
from sysmaint.core.runner import APT_ENV, apt_command, run_command

POSTFIX_MAIN_CF = Path("/etc/postfix/main.cf")
SASL_PASSWD_FILE = Path("/etc/postfix/sasl_passwd")

_DEBCONF_SELECTIONS = (
    "postfix postfix/main_mailer_type select Internet Site\n"
    "postfix postfix/mailname string localhost\n"
)

_POSTFIX_MAIN_CF = """\
# Generated by sysmaint postfix setup
relayhost = [smtp.gmail.com]:587
smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
smtp_sasl_security_options = noanonymous
smtp_tls_security_level = encrypt
smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt
inet_interfaces = loopback-only
"""


def execute(config: Config, logger: logging.Logger) -> None:
    """Install + configure Postfix as a Gmail relay end-to-end."""
    require_root()
    logger.info("Beginning Postfix Gmail relay setup")

    # Preconfigure to suppress the curses install dialog.
    _set_debconf_selections(logger)

    # Install the package non-interactively.
    run_command(apt_command(["update"]), timeout=600, env=APT_ENV, logger=logger)
    run_command(
        apt_command(["install", "postfix"]),
        timeout=600,
        env=APT_ENV,
        logger=logger,
    )

    # Write main.cf atomically via a temp file we then sudo-move.
    _write_root_owned_file(POSTFIX_MAIN_CF, _POSTFIX_MAIN_CF, mode=0o644, logger=logger)

    # Write the SASL password map. Format expected by postmap:
    #   [host]:port username:password
    sasl_line = (
        f"[{config.email.smtp_server}]:{config.email.smtp_port} "
        f"{config.email.from_addr}:{config.email.password}\n"
    )
    _write_root_owned_file(SASL_PASSWD_FILE, sasl_line, mode=0o600, logger=logger)

    # Hash it into the .db that Postfix actually consults.
    run_command(["postmap", str(SASL_PASSWD_FILE)], timeout=30, logger=logger)
    # postmap creates a .db file — lock it down too.
    db_file = SASL_PASSWD_FILE.with_suffix(SASL_PASSWD_FILE.suffix + ".db")
    if db_file.exists():
        run_command(["chmod", "600", str(db_file)], timeout=10, logger=logger)

    # Restart Postfix so it picks up the new config.
    run_command(["systemctl", "restart", "postfix"], timeout=60, logger=logger)
    run_command(["systemctl", "enable", "postfix"], timeout=30, logger=logger)

    logger.info("Postfix Gmail relay setup complete")


def _set_debconf_selections(logger: logging.Logger) -> None:
    """Feed Postfix preconfiguration into debconf via stdin.

    We use subprocess directly here because our standard runner doesn't
    yet support stdin input (and adding it for one caller would be overkill).
    """
    import subprocess  # local import — only used here

    logger.info("Preconfiguring Postfix via debconf-set-selections")
    proc = subprocess.run(
        ["debconf-set-selections"],
        input=_DEBCONF_SELECTIONS,
        text=True,
        capture_output=True,
        timeout=30,
        check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"debconf-set-selections failed (exit {proc.returncode}): {proc.stderr.strip()}"
        )


def _write_root_owned_file(
    path: Path, content: str, *, mode: int, logger: logging.Logger
) -> None:
    """Write `content` to `path` with the requested mode, owned by root.

    Writes via a temp file then atomically moves it into place. This avoids
    a window where the file exists but is empty or has wrong permissions.
    Caller must be root.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_suffix(path.suffix + ".sysmaint.tmp")
    tmp_path.write_text(content)
    tmp_path.chmod(mode)
    # os.replace is atomic on the same filesystem; we're under /etc so this is fine.
    tmp_path.replace(path)
    logger.info("Wrote %s (mode=%s)", path, oct(mode))
